#server:
#  port: 9088
#
## 网关运行基础中间件，包括但不限于下面中间件，能源和数能平台实例有所不同
#  # redis
#  # kafka
#  # pg
#  # es
#
## 设备下控消息中间件kafka配置
#spring:
#  profiles:
#    active: dev
#  application:
#    name: iot-gateway-new
#  redis:
#    host: 10.39.64.34
#    port: 6379
#    password: newiot@3edcvgy7
#    lettuce:
#      pool:
#        max-active: 512
#    timeout: 20s
#    serializer: fst
#  datasource:
#    url: jdbc:mysql://10.39.68.62:3306/dev_iot_connection_mng?sslMode=disabled&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#    username: adm_airecon
#    password: adm2o3rhU$2i
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 50
#      pool-name: DatebookHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#  kafka:
#    bootstrap-servers: 10.39.64.34:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer #配置序列化器
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      batch-size: 1024 #每次发送的消息数量
#      buffer-memory: 33554432
#      #procedure要求leader在考虑完成请求之前收到的确认数，用于控制发送记录在服务端的持久化，其值可以为如下：
#      #acks = 0 如果设置为零，则生产者将不会等待来自服务器的任何确认，该记录将立即添加到套接字缓冲区并视为已发送。在这种情况下，无法保证服务器已收到记录，并且重试配置将不会生效（因为客户端通常不会知道任何故障），为每条记录返回的偏移量始终设置为-1。
#      #acks = 1 这意味着leader会将记录写入其本地日志，但无需等待所有副本服务器的完全确认即可做出回应，在这种情况下，如果leader在确认记录后立即失败，但在将数据复制到所有的副本服务器之前，则记录将会丢失。
#      #acks = all 这意味着leader将等待完整的同步副本集以确认记录，这保证了只要至少一个同步副本服务器仍然存活，记录就不会丢失，这是最强有力的保证，这相当于acks = -1的设置。
#      #可以设置的值为：all, -1, 0, 1
#      acks: 1
#    consumer:
##      group-id: ${spring.application.name}-${spring.profiles.active} #group-id
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer #配置反序列化器
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
#      enable-auto-commit: true
#      auto-commit-interval: 100
#
## 网关连接器以及协议配置
#ennwiot:
#  serverId: node1
#  # 启动的网络组件
#  connector-mqtt:
#    name: 标准MQTT Connector
#    type: mqtt
#    configuration:
#      -
#        clientId: m1
#        port: 1883
#        host: 10.8.56.206
#        password: enn-iot
#        username: ByR6yILcsa
#        tls: false
#        tlsCert: ~/ssl/cert.pem
#        tlsKey: ~/ssl/key.pem
#        qos: 1
#        topics:
#          - data/KT150
#        protocol:
#          name: enn-mqtt-airwind
#          path: http://10.8.56.206:9000/device/enn-mqtt-airwind.jar
##          path: protocols-std-enn-general/enn-mqtt-airwind/target/enn-mqtt-airwind.jar
##              mainClass: com.ennewiot.gateway.protocol.NbAlarmDevMessageCodec
#          mainClass: cn.enncloud.iot.gateway.protocol.MqttAirWindMessageCodec
#          params:
#            p1: aaa
#            p2: bbb
#
#  connector-ctwing-mq:
#    name: ctwing mq Connector
#    type: ctwing-mq
#    configuration:
#      - server: 2000132971.mq-msgpush.ctwing.cn:16651
#        tenantId: 2000132971
#        token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMDAwMTMyOTcxIn0.hdVx5BWdAsCCHEkP-Xbz2v8ar1EX5FCJO41aAPnEEmw
#        topic: enn_data_iot_metric
#        description: 水培菜
#        protocol:
#          path: protocols-demo/gateway-protocol-json-demo/target/gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            p1: aaa
#            p2: bbb
#
#  connector-request:
#    name: xx 三方平台 Connector
#    type: request
#    jobType: local
#    configuration:
#      -
#        appid: yunyangaiot
#        server: latest
#        description: 水培菜
#        productId: 1711283717726924802
##        cron: 0 0/10 * * * ?
#        protocol:
#          path: protocols-udf/food-yunyangaiot-001/target/food-yunyangaiot-001.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.YunyangFoodProtocol
#          params:
#            metric: #右边是物模型测点
#              wec: ECwaterQuality
#              ah: H
#              wph: PHwaterQuality
#              at: Tair
#              online: Online
#
#      -
#        appid: yunyangaiot
#        server: batch
#        description: 水培菜
#        productId: 1711283717726924802
#        cron: 0 0/5 * * * ?
#        protocol:
#          path: protocols-udf/food-yunyangaiot-001/target/food-yunyangaiot-001.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.YunyangFoodBatchProtocol
#          params:
#            metric: #右边是物模型测点
#              wec: ECwaterQuality
#              ah: H
#              wph: PHwaterQuality
#              at: Tair
#              online: Online
#      -
#        appid: gpswv
#        server: gps
#        description: 河北金租-万位
#        productId: 1755166658968616962
#        protocol:
#          path: protocols-udf/car-jinzu-gpswv/target/car-jinzu-gpswv.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.GpswvMessageProtocol
#          params:
#            metric: #右边是物模型测点
#              lat: Latitude
#              lng: Longitude
#              gpsTime: TimePosition
#
#      -
#        appid: gpswv
#        server: mileage
#        description: 河北金租-万位
#        productId: 1755166658968616962
#        protocol:
#          path: protocols-udf/car-jinzu-gpswv/target/car-jinzu-gpswv.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.GpswvMileageProtocol
#          params:
#            '863114540563813': '17949748'
#            '863656040477254': '18894708'
#            '868035043180292': '61994872'
#            '863114540562752': '12190736'
#            '868035043298605': '88169841'
#            metric: #右边是物模型测点
#              mileage: MileageDailyDrive
#              duration: TimeDailyDrive #duration 是关键字
#
#      -
#        appid: wyiot
#        server: device
#        description: 河北金租-wy
#        productId: 1755166658968616962
#        cron: 0 0/6 * * * ?
#        protocol:
#          path: protocols-udf/car-jinzu-wy/target/car-jinzu-wy.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.WyDeviceProtocol
#          params:
#            productId: 1774720698073153538
#            tenantId: 1369559970221985794
#            deptId: 1574219727803117570
#            metric: #右边是物模型测点
#              voltage: voltage
#              electricLevel: electricLevel
#              signalNum: signalNum
#              current: current
#              position: position
#
#      -
#        appid: wyiot
#        server: asset
#        description: 河北金租-wy
#        productId: 1755166658968616962
##        cron: 0 0/10 * * * ?
#        protocol:
#          path: protocols-udf/car-jinzu-wy/target/car-jinzu-wy.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.WyAssetProtocol
#          params:
#            metric: #右边是物模型测点
#              electricity: electricity
#              workTimeSeconds: workTimeSeconds
#
#      -
#        appid: wyiot
#        server: alarm
#        description: 河北金租-wy
#        productId: 1755166658968616962
##        cron: 0 0/10 * * * ?
#        protocol:
#          path: protocols-udf/car-jinzu-wy/target/car-jinzu-wy.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.WyAlarmProtocol
#          params:
#            identifier: alarm
#            metric: #右边是物模型测点
#              alarmType: alarmType
#              deviceTime: deviceTime
#              alarmId: alarmId
#              serialNumber: serialNumber
#              alarmInfo: alarmInfo
#              endTime: endTime
#              posinfo: posinfo
#
#
#
#  connector-http:
#    name: 标准http Connector
#    type: http
#    configuration:
#      -
#        requestPath: gpswv
#        protocol:
#          path: protocols-udf/car-jinzu-gpswv/target/car-jinzu-gpswv.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.udf.GpswvAlarmProtocol
#          params:
#            '863114540563813': '17949748'
#            '863656040477254': '18894708'
#            '868035043180292': '61994872'
#            '863114540562752': '12190736'
#            '868035043298605': '88169841'
#            identifier: gpsAlarm
#            metric: #右边是物模型测点
#              alarmCode: alarmCode
#              lat: lat
#              lng: lng
#              imei: imei
#              time: t
#              speed: spd
#            mapping: #右边是物模型测点映射值
#              AREAOUT: 1
#              AREAIN: 2
#              FENCEOUT: 3
#              FENCEIN: 4
#              RISKPLACE: 5
#              OFFLINETIMEOUT: 6
#              STAYTIMEOUT: 7
#              OVERSPEED: 8
#              ABNORMALACCUMULATION: 9
#              SEP: 10
#              HOME: 11
#              ROUTE_OFFSET: 12
#              TURNOVER: 13
#              CRASH: 14
#              SHAKE: 14
#              LOWVOT: 15
#              REMOVE: 16
#              REMOVECONTINUOUSLY: 17
#              FASTACCELERATION: 18
#              FASTDECELERATION: 19
#              SHARPTURN: 20
#              ALARM_MILES_INTEVAL: 21
#              ALARM_MILES_TIMEOU: 21
#              STATION_CHANGE: 22
#
#
#
#  connector-dtu:
#    name: dtu Connector
#    type: dtu
#    configuration:
#      -
#        address: 0.0.0.0
#        port: 22602
#        bufferSize: 1024
#        description: 水培果
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            p1: aaa
#            p2: bbb
#
#      - address: 0.0.0.0
#        port: 22602
#        bufferSize: 1024
#        description: 水培果
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            p1: aaa
#            p2: bbb
#
#  connector-tcp:
#    server:
#      name: tcpTestServer
#      configuration:
#        - address: 0.0.0.0
#          port: 36001
#          parserType: LENGTH_FIELD
#          parserParams:
#            byteOrder: LITTLE_ENDIAN
#            maxLength: 10240
#            lengthFieldOffset: 13
#            lengthFieldLength: 2
#            lengthAdjustment: 3
#            initialBytesToStrip: 0
#          protocol:
#            path: http://10.8.56.206:9000/device/std-enn-tcp-jar-with-dependencies.jar
#            mainClass: cn.enncloud.iot.gateway.protocol.std.EnnStandardTcpProtocol
#            params:
#              p1: aaa
#              p2: bbb
#
#  connector-coap:
#    name: coap 连接器 Connector
#    type: socket-tcp
#    port: 2345
#    protocols:
#      - requestPath: test1
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            p1: aaa
#            p2: bbb
#
#      - requestPath: test2
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            p1: aaa
#            p2: bbb
#
#  connector-udp:
#    name: udp 连接器 Connector
#    type: udp
#    configuration:
#      -
#        port: 26001
#        description: 水培果
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            p1: aaa
#            p2: bbb
#  connector-snmp:
#    name: snmp 连接器 Connector
#    type: snmp
#    configuration:
#      -
#        address: 10.8.55.64
#        port: 161
#        retry: 2
#        timeout: 5000
#        version: 2
#        intervalMinute: 1
#        description: ECC800
#        protocol:
#          path: http://10.8.56.206:9000/device/std-snmp.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.snmp.SnmpProtocol
#          params:
#            OIDS: 1.3.6.1.4.1.2011.6.178.1.1.31.1.1.4.111,1.3.6.1.4.1.2011.6.178.1.1.31.1.1.4.112,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.2.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.16.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.17.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.90.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.166.4145,1.3.6.1.4.1.2011.6.178.1.1.112.2.1.28.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.5.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.86.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.165.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.7.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.170.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.117.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.141.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.9.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.169.4145,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.2.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.16.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.17.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.90.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.166.4146,1.3.6.1.4.1.2011.6.178.1.1.112.2.1.28.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.5.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.86.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.165.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.7.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.170.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.117.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.141.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.9.4146,1.3.6.1.4.1.2011.6.178.1.1.112.1.1.169.4146
#  connector-ftp:
#    name: ftp 连接器 Connector
#    type: ftp
#    configuration:
#      - address: 0.0.0.0
#        port: 26001
#        username: admin
#        password: admin
#        path: ftp://xxxx.com
#        intervalMinute: 5
#        description: 水培果
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            p1: aaa
#  connector-opcua:
#    name: opcua 连接器 Connector
#    type: opcua
#    configuration:
#      - endpointUrl: "opc.tcp://MS-JDIUVRNKJDPV:12686/milo"
#        username: admin
#        password: admin
#        intervalMinute: 5
#        description: 水培果
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            node1: xxxx
#            node2: xxxx
#
#  connector-opcua-asyncio:
#    name: opcua 连接器 Connector
#    type: opcua
#    configuration:
#      - endpointUrl: "opc.tcp://MS-JDIUVRNKJDPV:12686/milo"
#        username: admin
#        password: admin
#        intervalMinute: 5
#        description: 水培果
#        protocol:
#          path: \protocols-demo\gateway-protocol-json-demo\target\gateway-protocol-json-demo.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.demo.JsonDemoProtocol
#          params:
#            node1: xxxx
#            node2: xxxx

#  connector-bacnet:
#    name: bacnet 连接器 Connector
#    type: bacnet
#    configuration:
#      -
#        localBindAddress: 192.168.26.253
#        subnetAddress: 255.255.255.0
#        remoteAddress: 192.168.17.65
#        networkPrefixLength: 24
#        port: 47808
#        timeout: 6000
#        deviceNumber: 2654
#        description: device2654
#        intervalMinute: 1
#        cron:
#        objectType: analog-value
#        tablePath: http://192.168.26.251:9000/protocol-prod/BA_test_65.xls
#        protocol:
#          path: http://192.168.26.251:9000/protocol-prod/std-bacnet-ip.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.bacnet.BacnetIpProtocol

#      -
#        localBindAddress: 192.168.17.55
#        subnetAddress: 255.255.255.0
#        port: 502
#        description: device2655
#        intervalMinute: 1
#        objectType: analog-value
#        tablePath: http://10.39.68.54:9000/protocol-prod/Device_2655.xls
#        protocol:
#          path: http://10.39.68.54:9000/protocol-prod/std-bacnet-ip.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.bacnet.BacnetIpProtocol
#          params:
#            p1: aaa
#            p2: bbb
#      -
#        localBindAddress: 192.168.17.56
#        subnetAddress: 255.255.255.0
#        port: 502
#        description: device2656
#        intervalMinute: 1
#        objectType: analog-value
#        tablePath: http://10.39.68.54:9000/protocol-prod/Device_2656.xls
#        protocol:
#          path: http://10.39.68.54:9000/protocol-prod/std-bacnet-ip.jar
#          mainClass: cn.enncloud.iot.gateway.protocol.bacnet.BacnetIpProtocol
#          params:
#            p1: aaa
#            p2: bbb
#
#ennew:
#  iot:
#    other:
#      url: https://iot-gateway-other.dev.ennew.com/access
#    device:
#      url: https://iot-device-service.dev.ennew.com
#    topics:
#      topic: enn_data_iot_metric
#      eventTopic: data_iot_event
#      infoTopic: data_iot_device_info
#      commandTopic: device_command_topic
#      cloudTopic: iot_gateway_trdPlatform_data
#    switch:
#      filterMetric: false
#
#springdoc:
#  doc-info:
#    title: "物联网平台接入模块接口文档"
#  api-docs:
#    # 是否开启API文档，true表示开启，false表示关闭
#    enabled: true
#    groups:
#      # 是否开启分组，true表示开启
#      enabled: true
#    # API元数据访问路径，默认为/v3/api-docs
#    path: /v3/api-docs
#  swagger-ui:
#    # swagger-ui文档访问路径，默认为/swagger-ui.html
#    path: /swagger-ui.html
#  # 分组配置
#  group-configs:
#    - group: 1-设备接入网关web接口
#      # 按包路径匹配
#      packages-to-scan:
#        - cn.enncloud.iot.gateway.web
#
## 中瑞接口配置
#zy:
#  getTraffiCanalysisResInterfaceUrl: http://gatewayapi.lunz.cn/api/ApiPlat/GetTraffiCanalysisResInterface
#  getCarUserInfoYouLisUrl: https://gatewayapi.lunz.cn/api/ApiPlat/GetCarUserInfoYouLis
#  appKey: 05e1e4c8-bbc2-4cef-add5-342c071e1e4c
#  productId: 1762009328318734338
#  task:
#    computeDrivingDuration:
#      cron: 0 0/32 * * * ?
#    supplyImei:
#      cron: 0 0/23 * * * ?
#
#
#
#
#  ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
#  ### 执行器通讯TOKEN [选填]：非空时启用；
#  ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#  ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
#  ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#  ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
#  ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#  ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#xxl:
#  job:
#    admin:
#      addresses: http://10.39.64.22:9898/xxl-job-admin
#    accessToken: default_token
#    executor:
#      appname: iot-gateway-new
#      address:
#      ip: 10.20.37.69
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
#    api:
#      jobGroup: 2
#  ## local--本地调度。xxl--分布式调度（本地调度时执行job填写类名全路径”cn.enncloud.iot.gateway.timer.job.GatewayXxlJob“，分布式填写注解内定义名称）
#  enabled:
#    xxl: true
#    local: true
